version: '3.9'

services:
  db:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: fastapi_db

volumes:
  mysql_data:
